name: Continuous Integration

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cleanup
        run: sed -i "s/%NAME%/test/g" build.sc
      - name: Cache Scala
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
          apps: sbt
      - name: Install C++ build tools
        run: sudo apt-get install -y build-essential
      - name: Install Verilator from source
        run: |
          sudo apt-get install -y git autoconf flex bison build-essential
          git clone https://github.com/verilator/verilator.git
          cd verilator
          git checkout v5.008  # or latest stable
          autoconf
          ./configure
          make -j4
          sudo make install
          verilator --version
      - name: SBT Test
        run: sbt test
      # - name: mill Test
      #   run: mill _.test
